import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import React from "react";
import { FormModal } from "@components/formModal";

const Home: NextPage = () => {
  const [isOpenModal, setIsOpenModal] = useState(false);

  return (
    <div>
      <Head>
        <title>Task 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto">
        <div className="flex justify-center items-center h-screen">
          <button
            className="btn btn-red-800"
            onClick={() => setIsOpenModal(true)}
          >
            Open
          </button>

          {isOpenModal && (
            <FormModal
              isOpenModal={isOpenModal}
              setIsOpenModal={setIsOpenModal}
            />
          )}
        </div>
      </div>
    </div>
  );
};

export default Home;
